"""Markdown incident report exporter.

The output is what a Tier-2 analyst would paste into a Jira ticket or email
to leadership: human-readable, scannable, and complete enough to act on.
"""
from __future__ import annotations

from neural_architect.core.models import AttackChain


def to_markdown_report(chain: AttackChain) -> str:
    parts: list[str] = []
    parts.append(f"# Incident {chain.incident_id}\n")
    parts.append(f"**Severity:** {chain.severity.value.upper()}  ")
    if chain.started_at:
        parts.append(f"**First observed:** {chain.started_at.isoformat()}  ")
    if chain.ended_at:
        parts.append(f"**Last observed:** {chain.ended_at.isoformat()}  ")
    if chain.suspected_actor:
        parts.append(f"**Suspected actor:** {chain.suspected_actor}  ")
    parts.append("")
    parts.append("## Executive Summary")
    parts.append(chain.summary)
    parts.append("")

    if chain.events:
        parts.append("## Reconstructed Attack Chain")
        for i, ev in enumerate(chain.events, start=1):
            ts = ev.timestamp.isoformat() if ev.timestamp else "unknown time"
            techs = (
                ", ".join(f"{t.technique_id} ({t.name})" for t in ev.techniques) or "—"
            )
            parts.append(f"### {i}. {ev.phase.value.replace('_', ' ').title()}")
            parts.append(f"- **When:** {ts}")
            parts.append(f"- **Severity:** {ev.severity.value}")
            if ev.actor:
                parts.append(f"- **Actor:** {ev.actor}")
            if ev.target:
                parts.append(f"- **Target:** {ev.target}")
            parts.append(f"- **MITRE:** {techs}")
            parts.append("")
            parts.append(ev.description)
            if ev.evidence:
                parts.append("\n<details><summary>Evidence</summary>\n")
                parts.append("```")
                for line in ev.evidence[:10]:
                    parts.append(line)
                parts.append("```")
                parts.append("</details>\n")
            parts.append("")

    if chain.indicators:
        parts.append("## Indicators of Compromise")
        parts.append("| Type | Value |")
        parts.append("|------|-------|")
        for ind in chain.indicators[:200]:
            parts.append(f"| {ind.type.value} | `{ind.value}` |")
        parts.append("")

    if chain.recommended_actions:
        parts.append("## Recommended Actions")
        for action in chain.recommended_actions:
            parts.append(f"- {action}")
        parts.append("")

    if chain.model_notes:
        parts.append("## Model Notes & Caveats")
        parts.append(f"> {chain.model_notes}")
        parts.append("")

    parts.append("---")
    parts.append("*Generated by Neural Architect — AI-assisted DFIR. Verify before action.*")
    return "\n".join(parts)
